[package]
name = "vfx-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.10.0", features = ["v4"] }

[build-dependencies]
shac-rs = { git = "https://github.com/dearshuto/shac-rs.git" }
